### ISSUE TITLE
userid, applicationkey, space id  not saved after save

### ISSUE THREAD

**Issue by lschweizer** [pfpayments/opencart-3.0#1]
Hello, 
I just deploy your module on an opencart 3.0.3.2
when I try to configure the userid, applicationkey, space id  and I save the config he bring me back to the same page and all data are again empty.

any idea ?

BR
Laurent

**Comment by theodorspringwallee** [comment]
Dear [lschweizer](https://github.com/lschweizer)

Sorry for the late response.

Is this still an issue?

**Comment by theodorspringwallee** [comment]
If yes, please conact the PostFinance support: https://www.postfinance.ch/en/support/hotline.html
